### ISSUE TITLE
Log in with Azure account

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-registry-frontend#1]
Gebruikers moeten kunnen inloggen. Als start kiezen we voor Azure accounts om mee in te kunnen loggen. Dit issue is om deze in te bouwen.

Volgens onderstaande documentatie is dat alleen frontend werk?

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc

Gebaseerd op open standaarden, zoals OpenID, SAML, OAuth2

**Comment by RickSchager** [comment]
Vanuit EU H2020 SynchroniCity project zijn best leuke ideeën, kijk eens hier:
•	https://gitlab.com/synchronicity-iot/platform-deployment-docker/-/tree/master/manual
Bij 1. Platform architecture description, de security layer links.
Een stuk naar onderen een beschrijving van Security Layer met FIWARE (KeyRock + Wilma) componenten:
Of dit allemaal in praktijk goed en large scale  werkt????
Wel vanuit EU gepushed, gebaseerd op OAUT2, is veel subsidie ingezonken, men wil maximaal hergebruiken.
•	Een alternatief/implementatie hiervan voor onze Eindhoven omgeving gebruikt NGINX/X-Pack.

**Comment by marcvanandel** [comment]
We zouden ook voor Azure identities kunnen kiezen? Dat is wat Kadaster gebruikt ... en mogelijk diverse gemeentes ook?

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc

**Comment by RickSchager** [comment]
Denk het wel. We hebben een Microsoft E3 contract,  net als veel andere
gemeenten, via VNG Gemeenschappelijke Inkoop.
We gebruiken Azure AD met ADFS voor interne gebruikers. Of en hoe externen
te koppelen zijn, moet ik navragen.

MvG, Rick

**Comment by RickSchager** [comment]
https://solidproject.org/faqs#webid
Is dit iets??

**Comment by marcvanandel** [comment]
> https://solidproject.org/faqs#webid
> Is dit iets??

Dat is idd de richting waar ik aan zat te denken ... zonder dit te kennen 😉 Wat ik me nog wel afvraag is hoe we kunnen controleren dat de URL klopt en hoort bij degene die zich nu aanmeldt bij het SensRNet? Daarvoor hebben we toch een OpenID / OAuth2 / SAML 'iets' nodig, niet?

**Comment by kad-busses** [comment]
Integratie met AzureAD wordt verder opgepakt in https://github.com/kadaster-labs/sensrnet-home/issues/70
