### ISSUE TITLE
Remove kadaster-huisstijl from dependencies

### ISSUE THREAD

**Issue by kad-busses** [kadaster-labs/sensrnet-registry-frontend#101]
kadaster-huisstijl is a closed-source dependency which is blocking in building the code without a VPN connection to Kadaster. Extra caution has to be made to what extent this breaks the current interface. It should be roughly OK, as we still use Bootstrap 4 and kadaster-huisstijl is based off of Bootstrap 3. Samen oppakken met #104 omdat GGC hier gebruik van maakt.

**Comment by marcvanandel** [comment]
Misschien kunnen we gebruik maken van VNG/CommonGround Design System (van wat daar van bestaat)?
