### ISSUE TITLE
GGC vervangen door OpenLayers

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-registry-frontend#104]

**Comment by kad-busses** [comment]
Het gebruik van de generieke geo componenten bevat onze open-source code nog closed-source afhankelijkheden. Hierdoor kunnen andere partijen onze front-end code niet bouwen. Ook kunnen we hierdoor geen CI/CD pipeline opzetten.

We maken momenteel gebruik van:
plugin | toepassing
------- | -------
generieke-geo-componenten-map | tonen van de kaart
generieke-geo-componenten-dataset-legend <br> generieke-geo-componenten-dataset-tree | inladen van wms kaartlagen
generieke-geo-componenten-feature-info | tonen van feature info -> gebruiken we dit nog?
generieke-geo-componenten-search | de zoekbalk om naar locatie te gaan

Al deze componenten zijn reeds geschreven voor OpenLayers

**Comment by marcvanandel** [comment]
Mooi lijstje, @kad-busses ! Maken de GGC comps deze zaken echt gemakkelijker? Of bevatten zij de PDOK instellingen of zo? Wat maakt dat wij deze componenten gebouwd en gebruikt hebben? En waarom zou dat niet _in_ OpenLayers moeten zitten?

**Comment by kad-busses** [comment]
GGC is in zijn geheel nog wel een stuk groter dan wat wij nu gebruiken. Eigenlijk gebruiken we maar een klein deel ervan, en hebben zelf functionaliteiten al toegevoegd die voor ons nog ontbraken. Een mooie demo van alle functionaliteiten van de GGC kun je vinden op https://exampleapp.ggc.kadaster.nl/. De map en feature-info gebruiken ook echt openlayers dependencies, de overigen zijn map agnostisch, naar mijn weten.

Ik ben zeker geen expert op het gebied van GGC, maar zoals ik het begrijp maakt het echt een aantal zaken eenvoudiger, zoals de interactie tussen de verschillende componenten. En zo maakt het zoekcomponent gebruik van het nationaalgeoregister om locaties op te zoeken. Ook bevatten de componenten al consistente styling. Een aantal van de functionaliteiten zijn ook wel beschikbaar voor openlayers als community plugins, maar die moet je vervolgens nog zelf aan elkaar knutselen. Met GGC is dat dus al gedaan en updaten ze de componenten ook bij nieuwe Angular versies. Zeker omdat binnen het Kadaster meerdere kaartapplicaties in ontwikkeling zijn, heeft GGC grote toegevoegde waarde.
