### ISSUE TITLE
Waarschuwing toevoegen bij het formulier met publieke contactgegevens dat er geen persoonlijke contactgegevens ingevoerd mogen worden (DPIA tip)

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-registry-frontend#136]
Kunnen we hier een controle toevoegen om hier uitsluitend vaste patronen toe te staan? Dit om te voorkomen dat iemand per ongeluk zijn eigen emailadres toevoegt ... welke uiteindelijk niet meer vergeten kan worden in de distributed ledger

**Comment by marcvanandel** [comment]
@kad-floriw , in de frontend wordt toch ook een melding gegeven voor het emailveld? Dan is dit issue (dus) al klaar, right?

**Comment by kad-floriw** [comment]
> @kad-floriw , in de frontend wordt toch ook een melding gegeven voor het emailveld? Dan is dit issue (dus) al klaar, right?

Klopt! Deze kan gesloten worden
