### ISSUE TITLE
Themes veld alfabetisch sorteren

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-registry-frontend#146]
De thema's in `Datastream` zijn gesorteerd zoals deze in de KOOP lijst zijn opgenomen. Dat lijkt een random volgorde.

Het is logischer als deze alfabetisch is gesorteerd

![image](https://user-images.githubusercontent.com/2315396/113984287-34c18900-984b-11eb-9663-f11e4bd3ffac.png)

**Comment by marcvanandel** [comment]
@robhaans hoe kijk jij hier tegenaan?

**Comment by robhaans** [comment]
Eens. Voor het zoeken logisch. Pas bij grotere lijsten wil je op groepen clusteren.
