### ISSUE TITLE
"Opgeslagen!" melding soms foutief

### ISSUE THREAD

**Issue by kad-busses** [kadaster-labs/sensrnet-registry-frontend#211]
In onderstaand voorbeeld mislukt het verzoek om een bestaande sensor te updaten (er wordt geprobeerd een sensor uit een andere node aan te passen). Het PUT verzoek faalt terecht, maar toch komt er "Opgeslagen!" in beeld.

![image](https://user-images.githubusercontent.com/56066664/156192188-81fb8960-54b7-4d6c-94f4-9e3d6b4172ca.png)

**Comment by marcvanandel** [comment]
Ligt hier een extra bug onder? Het kunnen bewerken van een Device uit een andere Registry Node, zou helemaal niet als knop zichtbaar moeten zijn ... wel? Is dat nu wel zo? Moet hier een aparte bug voor opgevoerd worden ... of nemen we dat gewoon mee in dit issue?

**Comment by kad-busses** [comment]
Het is ook niet als knop zichtbaar, je ziet dan alleen "bekijken". Het bekijken en het bewerken formulier is in de front-end echter hetzelfde formulier. Het waren echter ooit twee verschillende formulieren. Eigenlijk moet het enkele formulier nu dus aangepast, bijvoorbeeld alle velden read-only en geen opslaanknop...
