### ISSUE TITLE
Set up Registry webapp - comp 1

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-registry-frontend#3]
Initial set up van de Registry webapp component (component 1 in de [architectuur](https://github.com/kadaster-labs/sensrnet-home/blob/master/docs/Architecture.md#componenten))

Dit issue heeft grote relatie met Registry backend kadaster-labs/sensrnet-registry-backend#5 

Hier zijn nog keuzes te maken:
1. Nemen we [Slimme apparaten van Amsterdam](https://github.com/Amsterdam/register-slimme-apparaten-frontend) als basis? Of
2. Nemen we SensorPilot als basis ... maar dan beginnen we wel opnieuw op basis van deze [blog](https://medium.com/@qasimsoomro/building-microservices-using-node-js-with-ddd-cqrs-and-event-sourcing-part-1-of-2-52e0dc3d81df) (namelijk event-sourced) en omdat SensorPilot een geïntegreerde frontend+backend applicatie is.

**Comment by marcvanandel** [comment]
@kad-griftj, volgens mij heb je wel een aardig goeie basis neergezet. Is het een idee om 's een PR te maken naar de `master` branch? Dan kunnen volgende wijzigingen mbv volgende PRs worden gereviewd? Of vind je het nog te vroeg daarvoor?

**Comment by kad-griftj** [comment]
@marcvanandel Wat mij betreft wachten we daar nog even mee, omdat het op sommige plekken nogal rommelig is. Ik heb nog wel wat tijd nodig om een goede basis neer te zetten.

**Comment by marcvanandel** [comment]
Is het er nu wel tijd voor, @kad-griftj ? 😉

**Comment by kad-griftj** [comment]
Laten we dat morgen doen, vandaag werk ik aan een ander project:)
