### ISSUE TITLE
Sensors op dezelfde locatie worden niet apart weergegeven

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-registry-frontend#30]
Uit testdag#1. 

Sensoren die op dezelfde locatie (met welke marge?) op de kaart worden weergegeven, worden gebundeld weergegeven. Deze zouden, vergelijkbaar als [SensorPilot](https://github.com/kadaster-labs/sensrnet-home/blob/master/images/SensorPilot/viewer-1.png), apart moeten worden weergegeven (vanaf bepaalde schaal?) met lijntje naar de locatie (oid).

**Comment by kad-busses** [comment]
Fixed in #38
