### ISSUE TITLE
Register Sensor: Meerdere 'submit after' opties (oa tbv bulk-invoer)

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-registry-frontend#31]
Uit testdag#1.

Op dit moment wordt het formulier niet leeg gemaakt als een sensor geregistreerd is/wordt. Dat zou wel handig(er) / logisch zijn. Aan de andere kant is het wel snel meerdere van dezelfde sensoren opvoeren. Zouden we een optie van 'Create alike' oid moeten toevoegen zodat het formulier dan niet leeg gemaakt wordt, terwijl het standaard wel wordt leeg gemaakt?

Het lijkt me goed als de locatie dan wel leeg gemaakt wordt? 🤔 

Scenario:
Als ik het formulier om een sensor te registreren heb ingevuld,
kan ik kiezen voor:
- Submit (& Close form)
- Submit+New with same location (& Clear form)
- Submit+New with same properties (& Clear location -> see #27 )

**Comment by marcvanandel** [comment]
Comments uit testers:

> Eigenlijk zie ik drie invulvarianten: onafhankelijke sensoren, meer dezelfde of verschillende sensoren op dezelfde plek, dezelfde sensoren op meerdere plekken. Bulk-invoer is wel wenselijk.

**Comment by kad-vossef** [comment]
link met #90
