### ISSUE TITLE
Locate me werkt niet

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-registry-frontend#32]
Uit testdag#1.

**Comment by kad-busses** [comment]
Hier is HTTPS voor nodig. De browsers weigeren Geolocatie over HTTP te verzenden. De feature werkt al wel tijdens het developen 😊

**Comment by kad-busses** [comment]
Feature is nu ook te bewonderen op 
https://viewer-sensrnet.etc.test.cloud.kadaster.nl/
