### ISSUE TITLE
Register Sensor: Locatie opgegeven (of juist niet) duidelijker zichtbaar maken

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-registry-frontend#33]
Bij het registreren van een sensor wil ik als gebruiker duidelijk zichtbaar hebben of ik een locatie geselecteerd heb voor deze sensor of niet.

- Button 'Select location' kleurtje geven?
- Punt op de kaart groter maken?
- Kunnen navigeren naar opgegeven locatie?

**Comment by kad-busses** [comment]
Fixed in #48, select knop wordt nu groen met een vinkje ✅
