### ISSUE TITLE
Standaard layer per gebruiker bewaren

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-registry-frontend#34]
Uit testdag#1.

**Comment by kad-busses** [comment]
Dit zou gaan (als ik het me goed herinner) over het bewaren van de laatste achtergrondlaag, locatie en zoomniveau. Wanneer een gebruiker opnieuw inlogt, of nieuwe sensoren opvoert, laat de kaart gelijk je eigen 'view' zien. Zou per gebruiker kunnen, of per node.

**Comment by rsleebos** [comment]
Nice2Have
