### ISSUE TITLE
Menu layout moet behouden blijven bij window resize

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-registry-frontend#36]
Uit testdag#1. 

Bij verschillende formaten van de browser, ziet het menu er anders uit. Soms komt 'Owner' naast de titel ipv eronder. Soms is de blauwe achtergrond kleiner dan de dropdown menu's.

**Comment by kad-busses** [comment]
Fixed in #40, er wordt nu de hele breedte gebruikt voor de navbar. Hiermee moet de responsiveness bevorderd worden
