### ISSUE TITLE
Sensor registratie layout ontwerp

### ISSUE THREAD

**Issue by kad-busses** [kadaster-labs/sensrnet-registry-frontend#42]
Welke kant willen we op met de formulieren voor sensoren registeren? Zeker straks met de toevoeging van datastreams wordt het te veel om alles in 1 lang formulier te plaatsen. 

1 van de opties is een stepper gebruiken: bijv:
https://material.angular.io/components/stepper/overview

**Comment by marcvanandel** [comment]
#106
