### ISSUE TITLE
SensorForm: Documentation URL hoeft niet verplicht te zijn

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-registry-frontend#43]
Uit testdag#2.

De documentatie URL is nu verplicht, maar dat hoeft ie niet te zijn, volgens mij. 

Daarnaast is het onduidelijk dat deze verplicht of fout is (ongeldig formaat), want dat wordt niet (goed) teruggekoppeld in de UI

**Comment by kad-vossef** [comment]
Uitwerken obv datamodel - https://github.com/kadaster-labs/sensrnet-home/issues/28
