### ISSUE TITLE
SensorForm: Theme past niet (goed) in het scherm

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-registry-frontend#45]
Uit testdag#2.

De dropdown van het veld Theme past niet goed in het formulier als het scherm te klein is. Scrollen e.d. werkt wat vreemd.

Oplossingsrichting: #42 ?

**Comment by kad-busses** [comment]
In #48 is het veld simpelweg wat hoger in het formulier geplaatst, waardoor die op de meeste schermen nu wél past. Dit is het enige element wat nog niet gebruikt wordt bij sensor updaten, wat komt door technische limitaties. Waarschijnlijk gaat dit element vervangen worden met een alternatieve implementatie, dan zullen we ook last meer hebben van het off-screen uitklappen
