### ISSUE TITLE
Update my sensors only

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-registry-frontend#46]
Uit testdag#2.

Het is mogelijk om 'Update Sensor' te doen op sensoren die van een andere eigenaar zijn... 🙈 

Eerst oplossing is dat dit voorkomen moet worden. Later kan die nog wel verder uitgebreid worden met rechten tbv service contracters e.d.

**Comment by kad-vossef** [comment]
Voorstel: sprint 5
