### ISSUE TITLE
Sensor kan niet worden verplaatst naar andere sensor

### ISSUE THREAD

**Issue by kad-busses** [kadaster-labs/sensrnet-registry-frontend#62]
Bij het updaten van de locatie van een sensor kan er niet voor gekozen worden om dezelfde locatie te gebruiken waar reeds een andere sensor staat. Bij het klikken op die locatie wordt de reeds daar liggende sensor geselecteerd en wordt de update flow afgebroken.

**Comment by kad-vossef** [comment]
Is gelijk aan #80
