### ISSUE TITLE
Eenheid van hoogte (?) en hoogte van een sensor in decimalen kan alleen met een punt

### ISSUE THREAD

**Issue by kad-vossef** [kadaster-labs/sensrnet-registry-frontend#68]
Het kan nu met zowel een punt als een komma maar het moet duidelijk zijn welke gebruikt moet worden. Ook de eenheid moet duidelijk zijn (meter/centimeter?).

**Comment by kad-bloemy** [comment]
Wat is de status van dit issue?

**Comment by kad-vossef** [comment]
Goede vraag, ik zie dat de eenheid inmiddels duidelijk is en dat zowel punt als komma toegestaan is. Verander je de hoogte (bv van 1.21 naar 1,22) dan wordt een punt automatisch een komma.

**Comment by marcvanandel** [comment]
Ik vraag me af hoe dit verschilt tussen browsers, met name met NL als basis of EN als basis 🤔 Misschien nog 's testen als de UI opnieuw is opgeleverd?

**Comment by marcvanandel** [comment]
Er is slechts één optie mogelijk ... wel afhankelijk van de taal van de browser
