### ISSUE TITLE
Layers – bij selecteren van andere laag valt de tekst op elkaar

### ISSUE THREAD

**Issue by kad-vossef** [kadaster-labs/sensrnet-registry-frontend#71]
Bij het selecteren van andere layer valt de tekst behorende bij de verschillende layers op elkaar. Dit lijkt afhankelijk te zijn van de browser. Edge heeft dit wel, Chrome niet.

**Comment by kad-vossef** [comment]
Browser test uitvoeren

**Comment by marcvanandel** [comment]
Is opgelost (ondertussen)
