### ISSUE TITLE
Update sensor – sensor verplaatsen naar een plek waar al een andere sensor staat lukt niet

### ISSUE THREAD

**Issue by kad-vossef** [kadaster-labs/sensrnet-registry-frontend#80]
Update sensor – tijdens een update de locatie van de sensor verplaatsen naar een plek waar al een andere sensor staat lukt niet. Het locatiepunt verschuift wel maar dan worden de gegevens van de nieuw aangeklikte sensor overgenomen in het update scherm.
=> Werkt inderdaad niet goed. Via ‘update sensor’ de locatie van een sensor op dezelfde locatie als een andere sensor plaatsen moet worden aangepast.

**Comment by marcvanandel** [comment]
Link to #106
