### ISSUE TITLE
Verzoek nieuwe functionaliteit - zoeken of filteren op criteria

### ISSUE THREAD

**Issue by kad-vossef** [kadaster-labs/sensrnet-registry-frontend#82]
Het zou mooi zijn om te kunnen zoeken of filteren op criteria (bv sensortype).
=> De zoekfunctie kan veel uitgebreider. Zoeken of filteren op locatie, sensortype etc. zal in een later stadium worden bekeken en uitgebreid.

**Comment by marcvanandel** [comment]
Duplicate van #131 . Wel nieuw issue voor central-viewer opgevoerd: https://github.com/kadaster-labs/sensrnet-central-viewer/issues/55
