### ISSUE TITLE
Engelse taal als standaard - Nederlands als optie (intl vs local)

### ISSUE THREAD

**Issue by kad-vossef** [kadaster-labs/sensrnet-registry-frontend#83]
Er zijn verschillende bevindingen gemeld over de taal. Het is de bedoeling om later een keuze te kunnen maken tussen (in eerste instantie) Nederlands en Engels. De termen zullen dan consequent in het Nederlands of in het Engels worden weergegeven.

Standaard kiezen we voor Engels als de taal die we gebruiken in de code. i18n (internationalization) is al toegevoegd als feature en daarmee wordt het mogelijk om (direct: kost nu extra tijd of later) extra talen, waaronder NL, toegevoegd kunnen worden.

**Comment by marcvanandel** [comment]
Hoe duur is het onderhouden van de code in Engels + Nederlandse vertaling?

**Comment by marcvanandel** [comment]
Nog eens over nadenkende: Het data model is Engels, vooral omdat dit internationale standaarden zijn, zoals SensorThingsAPI en Smart City standaarden. De data is (dus) Engels. De velden in de HTML zijn (dan ook) Engels. Alleen de labels zijn dan Nederlands ...
Dat is niet zo mooi in de code. En niet 'inclusief' voor niet-Nederlands (native) ontwikkelaars.

Daarom wil ik voorstellen om juist *Engels* als 'default' 😉 taal te gebruiken en de Nederlandse vertaling voor de labels te onderhouden. Een alternatief cq variatie is om de velden uit het data model vooral Engels te houden. Of helemaal geen Nederlands te ondersteunen.
-> is dit een serieuze optie? Waren de comments die we eerder hebben ontvangen op de 'walking skeleton release' niet vooral gericht op inconsistentie en niet (per se) op de Engelse vertaling?

Overigens kunnen we de Nederlandse vertalingen periodiek onderhouden worden, bijvoorbeeld voorafgaand aan elke grotere release? (in geval van continuous delivery is dat wellicht juist weer minder handig)
