### ISSUE TITLE
Layers – bij het aanzetten van de BAG-layer wijzigt er niets

### ISSUE THREAD

**Issue by kad-vossef** [kadaster-labs/sensrnet-registry-frontend#84]
De BAG layer werkt pas op een specifiek zoom-niveau. Maar dan lijkt er inderdaad geen BAG-objecten te verschijnen. Dit heeft wellicht te maken met de gebruikte browser en moet worden onderzocht.

**Comment by marcvanandel** [comment]
Vervangen van de oude (en vervallen 🙄 ) kaart layer door de nieuwe BAG layer
