### ISSUE TITLE
Layers – Inzoom en uitzoomen i.c.m. de BRT layer werkt niet (altijd)

### ISSUE THREAD

**Issue by kad-vossef** [kadaster-labs/sensrnet-registry-frontend#85]
Layers – zoom ver in, zet de BRT layer uit, zoom nog verder in, zet de BRT layer aan en er verschijnt niets meer. Bij ver uitzoomen weer wel.
=> Gedrag kan browserafhankelijk zijn. Gebruikte browser is Chrome.

**Comment by marcvanandel** [comment]
Op een grote schaal ingezoomd moet de BRT layer standaard vervangen worden door een andere kaartlaag zodat er tenminste iets te zien is? Of minder ver inzoomen? Of een duidelijke overgang tussen 'normaal zoom' en 'macro zoom' (oid) voor verder inzoomen?
