### ISSUE TITLE
Zoomlevel en locatie worden niet onthouden bij verversen scherm

### ISSUE THREAD

**Issue by kad-vossef** [kadaster-labs/sensrnet-registry-frontend#86]
Bij het verversen van het scherm (F5) worden zoomlevel en locatie niet onthouden en moet je opnieuw naar de gewenste locatie en zoomniveau. Dit is niet erg gebruiksvriendelijk.

**Comment by kad-busses** [comment]
Wordt verder verwerkt bij https://github.com/kadaster-labs/sensrnet-registry-frontend/issues/34
