### ISSUE TITLE
Pull down menu "Select theme" klapt niet in na selectie

### ISSUE THREAD

**Issue by kad-vossef** [kadaster-labs/sensrnet-registry-frontend#87]
Bij register sensor klapt het pull-down menu "Select theme" niet in na selectie, de andere pull-down menu`s wel.

**Comment by marcvanandel** [comment]
Won't fix in this way. Het is juist de bedoeling om meerdere themes te kunnen selecteren en dan zou het onhandig zijn als het pull down menu dichtklapt. Blijkbaar is dit te onduidelijk.

Oppakken met UX en WCAG issues
