### ISSUE TITLE
Verzoek nieuwe functionaliteit - Schaalbalk, noordpijl en overzichtskaartje

### ISSUE THREAD

**Issue by kad-vossef** [kadaster-labs/sensrnet-registry-frontend#89]
Graag een schaalbalk, noordpijl en overzichtskaartje.
=> We gaan hiernaar kijken. Schaalbalk is al eerder ter sprake gekomen en lijkt toegevoegde waarde te bieden. Noordpijl heeft dat m.i. minder vanwege de bevroren positie van de kaart. Niet helemaal duidelijk is wat met overzichtskaartje wordt bedoeld en welke functionaliteit hiermee samen zou moeten hangen (uitgezoomd kaartje van heel Nederland met rechthoek van waar ingezoomd is?). We komen hierop terug.

**Comment by marcvanandel** [comment]
Schaalbalk en noordpijl zijn gerealiseerd (laatste alleen bij afwijking van noord naar boven). Overzichtskaartje gaan we niet realiseren.
