### ISSUE TITLE
Update sensor – ingevoerde informatie wordt verwijderd

### ISSUE THREAD

**Issue by kad-vossef** [kadaster-labs/sensrnet-registry-frontend#93]
Update sensor – je kunt starten zonder een sensor te selecteren, de ingevoerde informatie wordt bij aanklikken van een sensor echter verwijderd.
=> Dit is niet gebruiksvriendelijk. Je zou pas een sensor moeten kunnen updaten nadat je hem hebt geselecteerd. Onderzoeken hoe het gemelde gedrag uit te sluiten is.

**Comment by marcvanandel** [comment]
Wordt opgelost met #106
