### ISSUE TITLE
Registreren gebruiker/owner – niet alle invoer mogelijkheden zijn relevant

### ISSUE THREAD

**Issue by kad-vossef** [kadaster-labs/sensrnet-registry-frontend#94]
-	Wat is het verschil tussen e-mail en public-email?
-	Registreren van phone-number en website lijkt me niet nodig (nu wel verplicht).
-	Tekst in het Engels

=> Wordt onderzocht. Het taal issue is al genoemd in bevinding 51 (frontend#83).

**Comment by marcvanandel** [comment]
Opgelost met nieuwe datamodel (+ realisatie)
